### ISSUE TITLE
Asset Tracker - v002

### ISSUE THREAD

**Issue by mohitbhoite** [spark/shields#58]
**List of hardware updates for the asset tracker (v002)**

- [x] Add x-y-z axis label for the accelerometer
- [x] Swap TX/RX labels
- [x] Add VIN label and voltage limits
- [x] Increase trace thickness for the 3V3 GPS supply
- [ ] Change bypass cap on the 3V3 GPS supply to 0.01uF from 0.1uF
- [x] Increase keep out area near the +ve terminal of CR1220 battery
- [ ] Change D6 pull-up from 10k to 2K2
- [ ] SMA pad in addition to uFL?
- [ ] Add microSD card for logging?
