### ISSUE TITLE
Asset Tracker - Issue tracker for v005

### ISSUE THREAD

**Issue by mohitbhoite** [spark/shields#62]
- [x] A0/A1 labels are swapped
- [x] Some through holes are not connected to SMD pads
- [x] RF switch (MAX2674) package is not DFM friendly  
- [x] Create a clear PCB stackup for 50Ω RF impedance trace
