### ISSUE TITLE
Internet Button: Issue tracker

### ISSUE THREAD

**Issue by mohitbhoite** [spark/shields#66]
Next revision:

- [ ] Remove GND plane under the Photon
- [ ] Retain silkscreen to be white
- [ ] Possible substitute to WS2813
